Removed the force that I did to get it working originally. We don't want it this way because we want the detection to actually work.
Now when a compile is run, we get the following:

In file included from ./common/ccoreio.h:26:0,
                 from rc5-72/cuda/r72cuda.h:12,
                 from rc5-72/cuda/r72cuda-1pipe.cu:14:
./common/cputypes.h:563:6: error: #error "Unknown CPU/OS detected in cputypes.h"
     #error "Unknown CPU/OS detected in cputypes.h"
      ^~~~~
./common/cputypes.h:564:6: error: #error "fix common/cputypes.h and/or compiler command line -Defines"
     #error "fix common/cputypes.h and/or compiler command line -Defines"
      ^~~~~
Makefile:208: recipe for target 'output/r72cuda-1pipe.o' failed
make: *** [output/r72cuda-1pipe.o] Error 1